#!/usr/bin/env python

from subprocess import call
import os

with open('priv/repo/entry_template.txt', 'r') as entry:
  parts = entry.read().split("\n")

  date = parts[0]
  title = parts[2]
  message = parts[4]
  captions = parts[6::2]

with open('priv/repo/new_entry.exs', 'r+') as script:
  script.truncate()
  script.write('# Script for adding a new entry the database. You can run it as:\n')
  script.write('#\n')
  script.write('#     mix run priv/repo/new_entry.exs\n\n')

  script.write('Journal.add_entry("%s", "%s", "%s")\n\n' % (title, message, date))

  for cap in captions:
    if cap == "@":
      cap = ""
    script.write('Journal.add_image("%s")\n' % cap)

  script.write('\nJournal.get_image_numbers(%d)\n' % len(captions))

call(["mix", "run", "priv/repo/new_entry.exs"])

if os.environ["MIX_ENV"] == "dev":
  call(["python", "/Users/Max/Documents/Work/Americorps/SLCC/journal-entries-script"])
